[main]
  # Print plain text without colors.
  text = False
  # Show `diff` when file content don't match. 
  diff = False
  # Exlude file list.
  ; Some files are automatically exluded to avoid "Too many levels of symbolic links" errors
  ; Refer to `self.excluded_href` at https://github.com/pafernanr/sosdiff/blob/main/sosdiff/lib/util.py#L20
  ; Below are recomended values
  exclude_files = 
    '^/date$',
    '^/df$',
    '^/free$',
    '^/sos_commands/.*/journalctl_.*$',
    '^/sos_commands/logs/.*$',
    '^/sos_strings/.*var\.log.*\.tailed$',
    '^/ps$',
    '^/var/log/.*$',
    '^/uptime$',
  # only-plugins = 'foreman', 'subscription_manager'
  # skip-plugins = 'foreman', 'subscription_manager'